export const books = [
  {
    image: "AGCNTS5.jpg",
    name: "All God's Children Need Travelling Shoes",
    author: "Maya Angelou",
    price: "£5.99",
    description: "THE FIFTH AUTOBIOGRAPHY",
    button: "Add To Bookcase",
  },
  {
    image: "ASFUTH6.jpg",
    name: "A Song Flung Up To Heaven",
    author: "Maya Angelou",
    price: "£3.99",
    description: "THE SIXTH AUTOBIOGRAPHY",
    button: "Add To Bookcase",
  },
  {
    image: "COBAB.jpg",
    name: "Children Of Blood And Bone",
    author: "Tomi Adeyemi",
    price: "£3.99",
    description: "WINNER OF THE TONIGHT SHOW SUMMER READS",
    button: "Add To Bookcase",
  },
  {
    image: "COVAV.jpg",
    name: "Children Of Virtue And Vengeance",
    author: "Tomi Adeyemi",
    price: "£0.99",
    description: "THE SEQUEL TO CHILDREN OF BLOOD AND BONE",
    button: "Add To Bookcase",
  },
  {
    image: "GTIMN2.jpg",
    name: "Gather Together In My Name",
    author: "Maya Angelou",
    price: "£4.99",
    description: "THE SECOND AUTOBIOGRAPHY",
    button: "Add To Bookcase",
  },
  {
    image: "IKWTCBS1.jpg",
    name: "I know Why The Caged Bird Sings",
    author: "Maya Angelou",
    price: "£5.99",
    description: "THE FIRST AUTOBIOGRAPHY",
    button: "Add To Bookcase",
  },
  {
    image: "MAMAM7.jpg",
    name: "Mom And Me And Mom",
    author: "Maya Angelou",
    price: "£5.99",
    description: "THE SEVENTH AUTOBIOGRAPHY",
    button: "Add To Bookcase",
  },
  {
    image: "Q.jpg",
    name: "Queenie",
    author: "Candice Carty-Williams",
    price: "£4.99",
    description: "THE SUNDAY TIMES BESTSELLER",
    button: "Add To Bookcase",
  },
  {
    image: "SASAGMLC3.jpg",
    name: "Singin' And Swingin' And Getting' Merry Like Christmas",
    author: "Maya Angelou",
    price: "£4.99",
    description: "THE THIRD AUTOBIOGRAPHY",
    button: "Add To Bookcase",
  },
  {
    image: "THOAW4.jpg",
    name: "The Heart Of A Woman",
    author: "Maya Angelou",
    price: "£3.99",
    description: "THE FOURTH AUTOBIOGRAPHY",
    button: "Add To Bookcase",
  },
  {
    image: "THUG.jpg",
    name: "The Hate U Give",
    author: "Angie Thomas",
    price: "£7.99",
    description: "THE NEW YORK TIMES BESTSELLER",
    button: "Add To Bookcase",
  },
  {
    image: "WIANLTTWPAR.jpg",
    name: "Why I'm No Longer Talking To White People About Race",
    author: "Reni Eddo-Lodge",
    price: "£7.49",
    description: "THE SUNDAY TIMES BESTSELLER",
    button: "Add To Bookcase",
  },
];
